// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics.CodeAnalysis;

using Schematrix.Data;

namespace Form2WebApp.Data
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial class tblEmploymentDuration
    {
        private static ItblEmploymentDurationPersister _DefaultPersister;
        private ItblEmploymentDurationPersister _Persister;
        private long _id;
        private string _descr;

        static tblEmploymentDuration()
        {
            // Assign default persister
            _DefaultPersister = new SqlServertblEmploymentDurationPersister();
        }

        public tblEmploymentDuration()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;
        }

        public tblEmploymentDuration(long _id)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign method parameter to private fields
            this._id = _id;

            // Call associated retrieve method
            Retrieve();
        }

        public tblEmploymentDuration(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign column values to private members
            for (int i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "ID":
                        this.id = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                    case "DESCR":
                        this.descr = (string)row[i, DataRowVersion.Current];
                        break;

                }
            }
        }

        public static ItblEmploymentDurationPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public ItblEmploymentDurationPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public long id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string descr
        {
            get { return _descr; }
            set { _descr = value; }
        }

        public virtual void Clone(tblEmploymentDuration sourceObject)
        {
            if (sourceObject == null)
            {
                throw new ArgumentNullException("sourceObject");
            }

            // Clone attributes from source object
            this._id = sourceObject.id;
            this._descr = sourceObject.descr;
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this);
        }

        public virtual int Update()
        {
            return _Persister.Update(this);
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this);
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this);
        }

        public static IReader<tblEmploymentDuration> ListAll()
        {
            return _DefaultPersister.ListAll();
        }

    }

    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial interface ItblEmploymentDurationPersister : IPersister
    {
        int Retrieve(tblEmploymentDuration tblEmploymentDuration);
        int Update(tblEmploymentDuration tblEmploymentDuration);
        int Delete(tblEmploymentDuration tblEmploymentDuration);
        int Insert(tblEmploymentDuration tblEmploymentDuration);
        IReader<tblEmploymentDuration> ListAll();
    }

    [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

    public partial class SqlServertblEmploymentDurationPersister : SqlPersisterBase, ItblEmploymentDurationPersister
    {
        public SqlServertblEmploymentDurationPersister()
        {
        }

        public SqlServertblEmploymentDurationPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServertblEmploymentDurationPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServertblEmploymentDurationPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(tblEmploymentDuration tblEmploymentDuration)
        {
            int __rowsAffected = 1;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEmploymentDurationGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.InputOutput;
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                    vdescr.Direction = ParameterDirection.Output;
                    sqlCommand.Parameters.Add(vdescr);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblEmploymentDuration.id);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        tblEmploymentDuration.id = SqlServerHelper.ToInt64(vid);
                        tblEmploymentDuration.descr = SqlServerHelper.ToString(vdescr);

                    }
                    catch (Exception ex)
                    {
                        if (ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0;
                        }
                        else
                        {
                            throw ex;
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Update(tblEmploymentDuration tblEmploymentDuration)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEmploymentDurationUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                vdescr.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vdescr);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vid, tblEmploymentDuration.id);
                SqlServerHelper.SetParameterValue(vdescr, tblEmploymentDuration.descr);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Delete(tblEmploymentDuration tblEmploymentDuration)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEmploymentDurationDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.Input;
                    sqlCommand.Parameters.Add(vid);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblEmploymentDuration.id);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Insert(tblEmploymentDuration tblEmploymentDuration)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEmploymentDurationInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.InputOutput;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                vdescr.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vdescr);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vid,
                    tblEmploymentDuration.id,
                    0);
                SqlServerHelper.SetParameterValue(vdescr, tblEmploymentDuration.descr);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                    // Get output parameter values
                    tblEmploymentDuration.id = SqlServerHelper.ToInt64(vid);

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public IReader<tblEmploymentDuration> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEmploymentDurationListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblEmploymentDurationReader(reader);
            }
        }

    }

    [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>")]

    public partial class SqlServertblEmploymentDurationReader : IReader<tblEmploymentDuration>
    {
        private SqlDataReader sqlDataReader;

        private tblEmploymentDuration _tblEmploymentDuration;

        private int _idOrdinal = -1;
        private int _descrOrdinal = -1;

        public SqlServertblEmploymentDurationReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader;
            for (int i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper();
                switch (columnName)
                {
                    case "ID":
                        _idOrdinal = i;
                        break;

                    case "DESCR":
                        _descrOrdinal = i;
                        break;

                }
            }
        }

        #region IReader<tblEmploymentDuration> Implementation

        public bool Read()
        {
            _tblEmploymentDuration = null;
            return this.sqlDataReader.Read();
        }

        public tblEmploymentDuration Current
        {
            get
            {
                if (_tblEmploymentDuration == null)
                {
                    _tblEmploymentDuration = new tblEmploymentDuration();
                    if (_idOrdinal != -1)
                    {
                        _tblEmploymentDuration.id = SqlServerHelper.ToInt64(sqlDataReader, _idOrdinal);
                    }
                    _tblEmploymentDuration.descr = SqlServerHelper.ToString(sqlDataReader, _descrOrdinal);
                }


                return _tblEmploymentDuration;
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<tblEmploymentDuration> ToList()
        {
            List<tblEmploymentDuration> list = new List<tblEmploymentDuration>();
            while (this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list;
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable;
        }

        #endregion

        #region IDisposable Implementation

        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion

        #region IEnumerable<tblEmploymentDuration> Implementation

        public IEnumerator<tblEmploymentDuration> GetEnumerator()
        {
            return new tblEmploymentDurationEnumerator(this);
        }

        #endregion

        #region IEnumerable Implementation

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new tblEmploymentDurationEnumerator(this);
        }

        #endregion

        [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

        private partial class tblEmploymentDurationEnumerator : IEnumerator<tblEmploymentDuration>
        {
            private IReader<tblEmploymentDuration> tblEmploymentDurationReader;

            public tblEmploymentDurationEnumerator(IReader<tblEmploymentDuration> tblEmploymentDurationReader)
            {
                this.tblEmploymentDurationReader = tblEmploymentDurationReader;
            }

            #region IEnumerator<tblEmploymentDuration> Members

            public tblEmploymentDuration Current
            {
                get { return this.tblEmploymentDurationReader.Current; }
            }

            #endregion

            #region IDisposable Members

            public void Dispose()
            {
                this.tblEmploymentDurationReader.Dispose();
            }

            #endregion

            #region IEnumerator Members

            object IEnumerator.Current
            {
                get { return this.tblEmploymentDurationReader.Current; }
            }

            public bool MoveNext()
            {
                return this.tblEmploymentDurationReader.Read();
            }

            public void Reset()
            {
                throw new Exception("Reset of tblemploymentduration reader is not supported.");
            }

            #endregion

        }
    }
}
