// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics.CodeAnalysis;

using Schematrix.Data;

namespace Form2WebApp.Data
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial class tblEducationalLevel
    {
        private static ItblEducationalLevelPersister _DefaultPersister;
        private ItblEducationalLevelPersister _Persister;
        private long _id;
        private string _name;

        static tblEducationalLevel()
        {
            // Assign default persister
            _DefaultPersister = new SqlServertblEducationalLevelPersister();
        }

        public tblEducationalLevel()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;
        }

        public tblEducationalLevel(long _id)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign method parameter to private fields
            this._id = _id;

            // Call associated retrieve method
            Retrieve();
        }

        public tblEducationalLevel(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign column values to private members
            for (int i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "ID":
                        this.id = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                    case "NAME":
                        this.name = (string)row[i, DataRowVersion.Current];
                        break;

                }
            }
        }

        public static ItblEducationalLevelPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public ItblEducationalLevelPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public long id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        public virtual void Clone(tblEducationalLevel sourceObject)
        {
            if (sourceObject == null)
            {
                throw new ArgumentNullException("sourceObject");
            }

            // Clone attributes from source object
            this._id = sourceObject.id;
            this._name = sourceObject.name;
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this);
        }

        public virtual int Update()
        {
            return _Persister.Update(this);
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this);
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this);
        }

        public static IReader<tblEducationalLevel> ListAll()
        {
            return _DefaultPersister.ListAll();
        }

    }

    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial interface ItblEducationalLevelPersister : IPersister
    {
        int Retrieve(tblEducationalLevel tblEducationalLevel);
        int Update(tblEducationalLevel tblEducationalLevel);
        int Delete(tblEducationalLevel tblEducationalLevel);
        int Insert(tblEducationalLevel tblEducationalLevel);
        IReader<tblEducationalLevel> ListAll();
    }

    [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

    public partial class SqlServertblEducationalLevelPersister : SqlPersisterBase, ItblEducationalLevelPersister
    {
        public SqlServertblEducationalLevelPersister()
        {
        }

        public SqlServertblEducationalLevelPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServertblEducationalLevelPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServertblEducationalLevelPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(tblEducationalLevel tblEducationalLevel)
        {
            int __rowsAffected = 1;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEducationalLevelGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.InputOutput;
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                    vname.Direction = ParameterDirection.Output;
                    sqlCommand.Parameters.Add(vname);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblEducationalLevel.id);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        tblEducationalLevel.id = SqlServerHelper.ToInt64(vid);
                        tblEducationalLevel.name = SqlServerHelper.ToString(vname);

                    }
                    catch (Exception ex)
                    {
                        if (ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0;
                        }
                        else
                        {
                            throw ex;
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Update(tblEducationalLevel tblEducationalLevel)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEducationalLevelUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                vname.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vname);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vid, tblEducationalLevel.id);
                SqlServerHelper.SetParameterValue(vname, tblEducationalLevel.name);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

        public int Delete(tblEducationalLevel tblEducationalLevel)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEducationalLevelDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.Input;
                    sqlCommand.Parameters.Add(vid);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblEducationalLevel.id);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Insert(tblEducationalLevel tblEducationalLevel)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEducationalLevelInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.InputOutput;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                vname.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vname);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vid,
                    tblEducationalLevel.id,
                    0);
                SqlServerHelper.SetParameterValue(vname, tblEducationalLevel.name);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                    // Get output parameter values
                    tblEducationalLevel.id = SqlServerHelper.ToInt64(vid);

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public IReader<tblEducationalLevel> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblEducationalLevelListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblEducationalLevelReader(reader);
            }
        }

    }

    [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>")]

    public partial class SqlServertblEducationalLevelReader : IReader<tblEducationalLevel>
    {
        private SqlDataReader sqlDataReader;

        private tblEducationalLevel _tblEducationalLevel;

        private int _idOrdinal = -1;
        private int _nameOrdinal = -1;

        public SqlServertblEducationalLevelReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader;
            for (int i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper();
                switch (columnName)
                {
                    case "ID":
                        _idOrdinal = i;
                        break;

                    case "NAME":
                        _nameOrdinal = i;
                        break;

                }
            }
        }

        #region IReader<tblEducationalLevel> Implementation

        public bool Read()
        {
            _tblEducationalLevel = null;
            return this.sqlDataReader.Read();
        }

        public tblEducationalLevel Current
        {
            get
            {
                if (_tblEducationalLevel == null)
                {
                    _tblEducationalLevel = new tblEducationalLevel();
                    if (_idOrdinal != -1)
                    {
                        _tblEducationalLevel.id = SqlServerHelper.ToInt64(sqlDataReader, _idOrdinal);
                    }
                    _tblEducationalLevel.name = SqlServerHelper.ToString(sqlDataReader, _nameOrdinal);
                }


                return _tblEducationalLevel;
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<tblEducationalLevel> ToList()
        {
            List<tblEducationalLevel> list = new List<tblEducationalLevel>();
            while (this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list;
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable;
        }

        #endregion

        #region IDisposable Implementation

        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion

        #region IEnumerable<tblEducationalLevel> Implementation

        public IEnumerator<tblEducationalLevel> GetEnumerator()
        {
            return new tblEducationalLevelEnumerator(this);
        }

        #endregion

        #region IEnumerable Implementation

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new tblEducationalLevelEnumerator(this);
        }

        #endregion

        [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

        private partial class tblEducationalLevelEnumerator : IEnumerator<tblEducationalLevel>
        {
            private IReader<tblEducationalLevel> tblEducationalLevelReader;

            public tblEducationalLevelEnumerator(IReader<tblEducationalLevel> tblEducationalLevelReader)
            {
                this.tblEducationalLevelReader = tblEducationalLevelReader;
            }

            #region IEnumerator<tblEducationalLevel> Members

            public tblEducationalLevel Current
            {
                get { return this.tblEducationalLevelReader.Current; }
            }

            #endregion

            #region IDisposable Members

            public void Dispose()
            {
                this.tblEducationalLevelReader.Dispose();
            }

            #endregion

            #region IEnumerator Members

            object IEnumerator.Current
            {
                get { return this.tblEducationalLevelReader.Current; }
            }

            public bool MoveNext()
            {
                return this.tblEducationalLevelReader.Read();
            }

            public void Reset()
            {
                throw new Exception("Reset of tbleducationallevel reader is not supported.");
            }

            #endregion

        }
    }
}
