// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics.CodeAnalysis;

using Schematrix.Data;

namespace Form2WebApp.Data
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial class tblMunicipality
    {
        private static ItblMunicipalityPersister _DefaultPersister;
        private ItblMunicipalityPersister _Persister;
        private long _id;
        private string _name;
        private long _cityId;

        static tblMunicipality()
        {
            // Assign default persister
            _DefaultPersister = new SqlServertblMunicipalityPersister();
        }

        public tblMunicipality()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;
        }

        public tblMunicipality(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign column values to private members
            for (int i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "ID":
                        this.id = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                    case "NAME":
                        this.name = (string)row[i, DataRowVersion.Current];
                        break;

                    case "CITYID":
                        this.cityId = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                }
            }
        }

        public static ItblMunicipalityPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public ItblMunicipalityPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public long id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        public long cityId
        {
            get { return _cityId; }
            set { _cityId = value; }
        }

        public virtual void Clone(tblMunicipality sourceObject)
        {
            if (sourceObject == null)
            {
                throw new ArgumentNullException("sourceObject");
            }

            // Clone attributes from source object
            this._id = sourceObject.id;
            this._name = sourceObject.name;
            this._cityId = sourceObject.cityId;
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this);
        }

        public static IReader<tblMunicipality> ListAll()
        {
            return _DefaultPersister.ListAll();
        }

        public static IReader<tblMunicipality> ListForcityId(long cityId)
        {
            return _DefaultPersister.ListForcityId(cityId);
        }

    }

    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial interface ItblMunicipalityPersister : IPersister
    {
        int Insert(tblMunicipality tblMunicipality);
        IReader<tblMunicipality> ListAll();
        IReader<tblMunicipality> ListForcityId(long cityId);
    }

    [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

    public partial class SqlServertblMunicipalityPersister : SqlPersisterBase, ItblMunicipalityPersister
    {
        public SqlServertblMunicipalityPersister()
        {
        }

        public SqlServertblMunicipalityPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServertblMunicipalityPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServertblMunicipalityPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Insert(tblMunicipality tblMunicipality)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblMunicipalityInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.InputOutput;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 100);
                vname.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vname);
                SqlParameter vcityId = new SqlParameter("@cityId", SqlDbType.BigInt);
                vcityId.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vcityId);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vid,
                    tblMunicipality.id,
                    0);
                SqlServerHelper.SetParameterValue(vname, tblMunicipality.name);
                SqlServerHelper.SetParameterValue(vcityId, tblMunicipality.cityId);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                    // Get output parameter values
                    tblMunicipality.id = SqlServerHelper.ToInt64(vid);

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public IReader<tblMunicipality> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblMunicipalityListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblMunicipalityReader(reader);
            }
        }

        public IReader<tblMunicipality> ListForcityId(long cityId)
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblMunicipalityListForcityId"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vcityId = new SqlParameter("@cityId", SqlDbType.BigInt);
                vcityId.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vcityId);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vcityId, cityId);

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblMunicipalityReader(reader);
            }
        }

    }

    [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>")]

    public partial class SqlServertblMunicipalityReader : IReader<tblMunicipality>
    {
        private SqlDataReader sqlDataReader;

        private tblMunicipality _tblMunicipality;

        private int _idOrdinal = -1;
        private int _nameOrdinal = -1;
        private int _cityIdOrdinal = -1;

        public SqlServertblMunicipalityReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader;
            for (int i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper();
                switch (columnName)
                {
                    case "ID":
                        _idOrdinal = i;
                        break;

                    case "NAME":
                        _nameOrdinal = i;
                        break;

                    case "CITYID":
                        _cityIdOrdinal = i;
                        break;

                }
            }
        }

        #region IReader<tblMunicipality> Implementation

        public bool Read()
        {
            _tblMunicipality = null;
            return this.sqlDataReader.Read();
        }

        public tblMunicipality Current
        {
            get
            {
                if (_tblMunicipality == null)
                {
                    _tblMunicipality = new tblMunicipality();
                    if (_idOrdinal != -1)
                    {
                        _tblMunicipality.id = SqlServerHelper.ToInt64(sqlDataReader, _idOrdinal);
                    }
                    _tblMunicipality.name = SqlServerHelper.ToString(sqlDataReader, _nameOrdinal);
                    if (_cityIdOrdinal != -1)
                    {
                        _tblMunicipality.cityId = SqlServerHelper.ToInt64(sqlDataReader, _cityIdOrdinal);
                    }
                }


                return _tblMunicipality;
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<tblMunicipality> ToList()
        {
            List<tblMunicipality> list = new List<tblMunicipality>();
            while (this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list;
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable;
        }

        #endregion

        #region IDisposable Implementation

        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion

        #region IEnumerable<tblMunicipality> Implementation

        public IEnumerator<tblMunicipality> GetEnumerator()
        {
            return new tblMunicipalityEnumerator(this);
        }

        #endregion

        #region IEnumerable Implementation

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new tblMunicipalityEnumerator(this);
        }

        #endregion

        [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

        private partial class tblMunicipalityEnumerator : IEnumerator<tblMunicipality>
        {
            private IReader<tblMunicipality> tblMunicipalityReader;

            public tblMunicipalityEnumerator(IReader<tblMunicipality> tblMunicipalityReader)
            {
                this.tblMunicipalityReader = tblMunicipalityReader;
            }

            #region IEnumerator<tblMunicipality> Members

            public tblMunicipality Current
            {
                get { return this.tblMunicipalityReader.Current; }
            }

            #endregion

            #region IDisposable Members

            public void Dispose()
            {
                this.tblMunicipalityReader.Dispose();
            }

            #endregion

            #region IEnumerator Members

            object IEnumerator.Current
            {
                get { return this.tblMunicipalityReader.Current; }
            }

            public bool MoveNext()
            {
                return this.tblMunicipalityReader.Read();
            }

            public void Reset()
            {
                throw new Exception("Reset of tblmunicipality reader is not supported.");
            }

            #endregion

        }
    }
}
