// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics.CodeAnalysis;

using Schematrix.Data;

namespace Form2WebApp.Data
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial class tblOrientationGroup
    {
        private static ItblOrientationGroupPersister _DefaultPersister;
        private ItblOrientationGroupPersister _Persister;
        private long _id;
        private string _name;

        static tblOrientationGroup()
        {
            // Assign default persister
            _DefaultPersister = new SqlServertblOrientationGroupPersister();
        }

        public tblOrientationGroup()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;
        }

        public tblOrientationGroup(long _id)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign method parameter to private fields
            this._id = _id;

            // Call associated retrieve method
            Retrieve();
        }

        public tblOrientationGroup(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign column values to private members
            for (int i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "ID":
                        this.id = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                    case "NAME":
                        this.name = (string)row[i, DataRowVersion.Current];
                        break;

                }
            }
        }

        public static ItblOrientationGroupPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public ItblOrientationGroupPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public long id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        public virtual void Clone(tblOrientationGroup sourceObject)
        {
            if (sourceObject == null)
            {
                throw new ArgumentNullException("sourceObject");
            }

            // Clone attributes from source object
            this._id = sourceObject.id;
            this._name = sourceObject.name;
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this);
        }

        public virtual int Update()
        {
            return _Persister.Update(this);
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this);
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this);
        }

        public static IReader<tblOrientationGroup> ListAll()
        {
            return _DefaultPersister.ListAll();
        }

    }

    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial interface ItblOrientationGroupPersister : IPersister
    {
        int Retrieve(tblOrientationGroup tblOrientationGroup);
        int Update(tblOrientationGroup tblOrientationGroup);
        int Delete(tblOrientationGroup tblOrientationGroup);
        int Insert(tblOrientationGroup tblOrientationGroup);
        IReader<tblOrientationGroup> ListAll();
    }

    [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

    public partial class SqlServertblOrientationGroupPersister : SqlPersisterBase, ItblOrientationGroupPersister
    {
        public SqlServertblOrientationGroupPersister()
        {
        }

        public SqlServertblOrientationGroupPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServertblOrientationGroupPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServertblOrientationGroupPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(tblOrientationGroup tblOrientationGroup)
        {
            int __rowsAffected = 1;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblOrientationGroupGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.InputOutput;
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                    vname.Direction = ParameterDirection.Output;
                    sqlCommand.Parameters.Add(vname);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblOrientationGroup.id);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        tblOrientationGroup.id = SqlServerHelper.ToInt64(vid);
                        tblOrientationGroup.name = SqlServerHelper.ToString(vname);

                    }
                    catch (Exception ex)
                    {
                        if (ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0;
                        }
                        else
                        {
                            throw ex;
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Update(tblOrientationGroup tblOrientationGroup)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblOrientationGroupUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                vname.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vname);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vid, tblOrientationGroup.id);
                SqlServerHelper.SetParameterValue(vname, tblOrientationGroup.name);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Delete(tblOrientationGroup tblOrientationGroup)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblOrientationGroupDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.Input;
                    sqlCommand.Parameters.Add(vid);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblOrientationGroup.id);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Insert(tblOrientationGroup tblOrientationGroup)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblOrientationGroupInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.InputOutput;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vname = new SqlParameter("@name", SqlDbType.NVarChar, 255);
                vname.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vname);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vid,
                    tblOrientationGroup.id,
                    0);
                SqlServerHelper.SetParameterValue(vname, tblOrientationGroup.name);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                    // Get output parameter values
                    tblOrientationGroup.id = SqlServerHelper.ToInt64(vid);

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public IReader<tblOrientationGroup> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblOrientationGroupListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblOrientationGroupReader(reader);
            }
        }

    }

    [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>")]

    public partial class SqlServertblOrientationGroupReader : IReader<tblOrientationGroup>
    {
        private SqlDataReader sqlDataReader;

        private tblOrientationGroup _tblOrientationGroup;

        private int _idOrdinal = -1;
        private int _nameOrdinal = -1;

        public SqlServertblOrientationGroupReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader;
            for (int i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper();
                switch (columnName)
                {
                    case "ID":
                        _idOrdinal = i;
                        break;

                    case "NAME":
                        _nameOrdinal = i;
                        break;

                }
            }
        }

        #region IReader<tblOrientationGroup> Implementation

        public bool Read()
        {
            _tblOrientationGroup = null;
            return this.sqlDataReader.Read();
        }

        public tblOrientationGroup Current
        {
            get
            {
                if (_tblOrientationGroup == null)
                {
                    _tblOrientationGroup = new tblOrientationGroup();
                    if (_idOrdinal != -1)
                    {
                        _tblOrientationGroup.id = SqlServerHelper.ToInt64(sqlDataReader, _idOrdinal);
                    }
                    _tblOrientationGroup.name = SqlServerHelper.ToString(sqlDataReader, _nameOrdinal);
                }


                return _tblOrientationGroup;
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<tblOrientationGroup> ToList()
        {
            List<tblOrientationGroup> list = new List<tblOrientationGroup>();
            while (this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list;
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable;
        }

        #endregion

        #region IDisposable Implementation

        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion

        #region IEnumerable<tblOrientationGroup> Implementation

        public IEnumerator<tblOrientationGroup> GetEnumerator()
        {
            return new tblOrientationGroupEnumerator(this);
        }

        #endregion

        #region IEnumerable Implementation

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new tblOrientationGroupEnumerator(this);
        }

        #endregion

        [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

        private partial class tblOrientationGroupEnumerator : IEnumerator<tblOrientationGroup>
        {
            private IReader<tblOrientationGroup> tblOrientationGroupReader;

            public tblOrientationGroupEnumerator(IReader<tblOrientationGroup> tblOrientationGroupReader)
            {
                this.tblOrientationGroupReader = tblOrientationGroupReader;
            }

            #region IEnumerator<tblOrientationGroup> Members

            public tblOrientationGroup Current
            {
                get { return this.tblOrientationGroupReader.Current; }
            }

            #endregion

            #region IDisposable Members

            public void Dispose()
            {
                this.tblOrientationGroupReader.Dispose();
            }

            #endregion

            #region IEnumerator Members

            object IEnumerator.Current
            {
                get { return this.tblOrientationGroupReader.Current; }
            }

            public bool MoveNext()
            {
                return this.tblOrientationGroupReader.Read();
            }

            public void Reset()
            {
                throw new Exception("Reset of tblorientationgroup reader is not supported.");
            }

            #endregion

        }
    }
}
