// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics.CodeAnalysis;

using Schematrix.Data;

namespace Form2WebApp.Data
{
    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial class tblPopulation
    {
        private static ItblPopulationPersister _DefaultPersister;
        private ItblPopulationPersister _Persister;
        private long _id;
        private string _descr;

        static tblPopulation()
        {
            // Assign default persister
            _DefaultPersister = new SqlServertblPopulationPersister();
        }

        public tblPopulation()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;
        }

        public tblPopulation(long _id)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign method parameter to private fields
            this._id = _id;

            // Call associated retrieve method
            Retrieve();
        }

        public tblPopulation(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister;

            // Assign column values to private members
            for (int i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "ID":
                        this.id = Convert.ToInt64(row[i, DataRowVersion.Current]);
                        break;

                    case "DESCR":
                        this.descr = (string)row[i, DataRowVersion.Current];
                        break;

                }
            }
        }

        public static ItblPopulationPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public ItblPopulationPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public long id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string descr
        {
            get { return _descr; }
            set { _descr = value; }
        }

        public virtual void Clone(tblPopulation sourceObject)
        {
            if (sourceObject == null)
            {
                throw new ArgumentNullException("sourceObject");
            }

            // Clone attributes from source object
            this._id = sourceObject.id;
            this._descr = sourceObject.descr;
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this);
        }

        public virtual int Update()
        {
            return _Persister.Update(this);
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this);
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this);
        }

        public static IReader<tblPopulation> ListAll()
        {
            return _DefaultPersister.ListAll();
        }

    }

    [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

    public partial interface ItblPopulationPersister : IPersister
    {
        int Retrieve(tblPopulation tblPopulation);
        int Update(tblPopulation tblPopulation);
        int Delete(tblPopulation tblPopulation);
        int Insert(tblPopulation tblPopulation);
        IReader<tblPopulation> ListAll();
    }

    [SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>")]

    public partial class SqlServertblPopulationPersister : SqlPersisterBase, ItblPopulationPersister
    {
        public SqlServertblPopulationPersister()
        {
        }

        public SqlServertblPopulationPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServertblPopulationPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServertblPopulationPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(tblPopulation tblPopulation)
        {
            int __rowsAffected = 1;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblPopulationGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.InputOutput;
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                    vdescr.Direction = ParameterDirection.Output;
                    sqlCommand.Parameters.Add(vdescr);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblPopulation.id);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        tblPopulation.id = SqlServerHelper.ToInt64(vid);
                        tblPopulation.descr = SqlServerHelper.ToString(vdescr);

                    }
                    catch (Exception ex)
                    {
                        if (ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0;
                        }
                        else
                        {
                            throw ex;
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Update(tblPopulation tblPopulation)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblPopulationUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                vdescr.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vdescr);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vid, tblPopulation.id);
                SqlServerHelper.SetParameterValue(vdescr, tblPopulation.descr);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Delete(tblPopulation tblPopulation)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblPopulationDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                    vid.Direction = ParameterDirection.Input;
                    sqlCommand.Parameters.Add(vid);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vid, tblPopulation.id);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public int Insert(tblPopulation tblPopulation)
        {
            int __rowsAffected = 0;

            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblPopulationInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Add command parameters
                SqlParameter vid = new SqlParameter("@id", SqlDbType.BigInt);
                vid.Direction = ParameterDirection.InputOutput;
                sqlCommand.Parameters.Add(vid);
                SqlParameter vdescr = new SqlParameter("@descr", SqlDbType.NVarChar, 255);
                vdescr.Direction = ParameterDirection.Input;
                sqlCommand.Parameters.Add(vdescr);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vid,
                    tblPopulation.id,
                    0);
                SqlServerHelper.SetParameterValue(vdescr, tblPopulation.descr);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery();
                    if (__rowsAffected == 0)
                    {
                        return __rowsAffected;
                    }


                    // Get output parameter values
                    tblPopulation.id = SqlServerHelper.ToInt64(vid);

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }

            return __rowsAffected;
        }

        public IReader<tblPopulation> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("tblPopulationListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure;

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServertblPopulationReader(reader);
            }
        }

    }

    [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>")]

    public partial class SqlServertblPopulationReader : IReader<tblPopulation>
    {
        private SqlDataReader sqlDataReader;

        private tblPopulation _tblPopulation;

        private int _idOrdinal = -1;
        private int _descrOrdinal = -1;

        public SqlServertblPopulationReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader;
            for (int i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper();
                switch (columnName)
                {
                    case "ID":
                        _idOrdinal = i;
                        break;

                    case "DESCR":
                        _descrOrdinal = i;
                        break;

                }
            }
        }

        #region IReader<tblPopulation> Implementation

        public bool Read()
        {
            _tblPopulation = null;
            return this.sqlDataReader.Read();
        }

        public tblPopulation Current
        {
            get
            {
                if (_tblPopulation == null)
                {
                    _tblPopulation = new tblPopulation();
                    if (_idOrdinal != -1)
                    {
                        _tblPopulation.id = SqlServerHelper.ToInt64(sqlDataReader, _idOrdinal);
                    }
                    _tblPopulation.descr = SqlServerHelper.ToString(sqlDataReader, _descrOrdinal);
                }


                return _tblPopulation;
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<tblPopulation> ToList()
        {
            List<tblPopulation> list = new List<tblPopulation>();
            while (this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list;
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable;
        }

        #endregion

        #region IDisposable Implementation

        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion

        #region IEnumerable<tblPopulation> Implementation

        public IEnumerator<tblPopulation> GetEnumerator()
        {
            return new tblPopulationEnumerator(this);
        }

        #endregion

        #region IEnumerable Implementation

        IEnumerator IEnumerable.GetEnumerator()
        {
            return new tblPopulationEnumerator(this);
        }

        #endregion

        [SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]

        private partial class tblPopulationEnumerator : IEnumerator<tblPopulation>
        {
            private IReader<tblPopulation> tblPopulationReader;

            public tblPopulationEnumerator(IReader<tblPopulation> tblPopulationReader)
            {
                this.tblPopulationReader = tblPopulationReader;
            }

            #region IEnumerator<tblPopulation> Members

            public tblPopulation Current
            {
                get { return this.tblPopulationReader.Current; }
            }

            #endregion

            #region IDisposable Members

            public void Dispose()
            {
                this.tblPopulationReader.Dispose();
            }

            #endregion

            #region IEnumerator Members

            object IEnumerator.Current
            {
                get { return this.tblPopulationReader.Current; }
            }

            public bool MoveNext()
            {
                return this.tblPopulationReader.Read();
            }

            public void Reset()
            {
                throw new Exception("Reset of tblpopulation reader is not supported.");
            }

            #endregion

        }
    }
}
